qonto/database-monitoring-framework

content/getting-started.md
The old URL was the one for prometheus-rds-alerts-chart
=> content/getting-started: fix OCI URL for prometheus-postgresql-alerts-chart

content/runbooks/postgresql/PostgreSQLExporterDown.md, content/runbooks/postgresql/PostgreSQLExporterScrapingLimit.md, content/runbooks/postgresql/PostgreSQLInactiveLogicalReplicationSlot.md, content/runbooks/postgresql/PostgreSQLInactivePhysicalReplicationSlot.md, content/runbooks/postgresql/sql/list-replication-slots.sql
- improve formatting
- remove direct reference to RDS when possible
=> Improve various PostgreSQL runbooks

charts/prometheus-rds-alerts/values.yaml
Reduce replication lag threshold
Replication lag above 60s is already an alert
- Reduce replication lag threshold to 60s by default
=> Reduce replication lag threshold

charts/prometheus-postgresql-alerts/values.yaml, charts/prometheus-rds-alerts/values.yaml
Fix `additionalRuleLabels` default type
Helm report warnings when `additionalRuleLabels` is customized due to incorrect default variable type.
```
coalesce.go:289: warning: destination for prometheus-rules.prometheus-postgresql-alerts-chart.global.additionalRuleLabels is a table. Ignoring non-table value ([])
coalesce.go:289: warning: destination for prometheus-rules.prometheus-rds-alerts-chart.global.additionalRuleLabels is a table. Ignoring non-table value ([])
```
- Use `dict` as default value for `additionalRuleLabels`
=> Fix additionalRuleLabels default type

charts/prometheus-postgresql-alerts/values.yaml, content/runbooks/postgresql/PostgreSQLExporterErrors.md, content/runbooks/postgresql/PostgreSQLExporterMissingScrapeErrorMetric.md
The goal of this MR is to create two new alerts for the PostgreSQL exporter, aiming at detecting when the exporter is up, but is not scrapping properly. Such errors may indicate that some metrics are not being exposed or collected properly, resulting in a degraded monitoring system.
=> Add missing metrics alerts

charts/prometheus-postgresql-alerts/values.yaml
This MR fixes the metric named used in the newly introduced `PostgreSQLExporterMissingScrapeErrorMetric`alert.
=> fix(postgresql): use correct `pg_exporter_last_scrape_error` metric

.gitignore, CONTRIBUTING.md, charts/prometheus-rds-alerts/values.yaml
AWS documentation mention that if no user transactions are running on the source DB instance, the associated PostgreSQL read replica reports a replication lag of up to five minutes.
=> feat(rds): RDSReplicaLag bumped to 5 min

.github/ISSUE_TEMPLATE/changes.md, charts/prometheus-postgresql-alerts/values.yaml, charts/prometheus-rds-alerts/values.yaml
Aggregate metrics by labels
- Alert rules are not aggregated by `dbidentifier`. So when multiple exporters are deployed or scheduled in Kubernetes environment, it may prevent alerts.
- `aws_account_id` or `aws_region` labels are not matched, same `dbidentifier` is multiple accounts could lead to incorrect alerts
- Rewrite queries to use `max by (labels) (metrics)` style
- Add `aws_account_id` and `aws_region` label to support multiple-region
=> Aggregate metrics by labels

.github/workflows/release.yaml, docker-compose.yaml, docs/hugo-upgrade.md
Upgrade Hugo to 0.120.4
Use latest bug fixes
- Bump Hugo version in Github workflow
- Use `hugomods/hugo` docker image for local development
=> Upgrade Hugo to 0.120.4

charts/_source/templates/prometheusConfiguration.yaml, charts/_source/templates/prometheusRules.yaml, charts/_source/tests/prometheusRules_test.yaml, charts/_source/tests/values/with_PrometheusConfigurationFileFormat.yaml, charts/_source/values.yaml, charts/prometheus-postgresql-alerts/values.yaml, charts/prometheus-rds-alerts/values.yaml, content/faq.md, content/getting-started.md
Add Prometheus standalone configuration file format
This allows the deployment of DMF for standalone Prometheus deployments.
Rendering rules as valid Prometheus rule files will also help us with unit tests
- Add `format` parameter to render rules as Prometheus configuration rules file
- Add deployment in getting-started
=> Add Prometheus standalone configuration file format

.github/workflows/release.yaml, themes/patch_book.txt
Fix search engine
Hugo book built-in search engine is not loading, and linking correct documents when used in subdirectory.
Basically the template is using only relative links, see https://github.com/alex-shpak/hugo-book/pull/505
As workaround, we are patching the files, until upstream is fixed.
- Patch hugo-book to fix search engine
=> Fix search engine

charts/prometheus-rds-alerts/prometheus_tests/RDSCACertificateCloseToExpiration.yml, charts/prometheus-rds-alerts/values.yaml, content/runbooks/rds/RDSCACertificateCloseToExpiration.md
This commit adds a new alert that will trigger if it detects any instance with a CA certificate with an expiration date scheduled within the next 15 days.
=> feat(rds): add alerting on CA certificates expiration

content/runbooks/rds/RDSCACertificateCloseToExpiration.md
Not all Root CA expires in August 2024. A link has been added to a AWS blog post with expiration date of each region
=> chore(rds): RDSCACertificateCloseToExpiration: expiration date of root CA depends of the region

charts/prometheus-rds-alerts/prometheus_tests/RDSNonCPUUtilization.yml, charts/prometheus-rds-alerts/values.yaml
Reduce the severity of the `RDSNonCPUUtilization` alert.
A poorly configured application could easily trigger this alert if it didn't manage advisory locks correctly.
While RDSNonCPUUtilization is a strong indicator that the system is underperforming, it doesn't justify raising `critical` alerts.
- Set severity from `critical` to `warning`
=> Reduce the severity of the RDSNonCPUUtilization alert

charts/prometheus-rds-alerts/prometheus_tests/RDSNonCPUUtilization.yml
https://github.com/qonto/database-monitoring-framework/pull/18 changed the description but the PR has been merged with the failing test
=> fix(test): Fix RDSNonCPUUtilization description

content/tutorials/postgresql-exporter.queries.yaml
Methods computing size of tables or related objects (such as `pg_total_relation_size` or `pg_table_size`) acquires an AccessShareLock. This happens while refreshing a Materialized View or when ALTER'ing a table.
A fix has been implemented to estimate (very precisely) the size of materialized views, so the query does not wait while a materialized view is being refreshed. However, this did not fix the issue when a table is being ALTER'ed: the SQL query waits for the AccessExclusiveLock being released, and this can take several minutes. It is an issue because the exporter stops exporting any data while the ALTER is running.
To prevent that, we check in `pg_locks` table if an AccessExclusiveLock exists: if it does exist, we skip it:
- the exporter will compute size for tables with no …
=> chore(queries): pg_stat_user_tables: skip tables with an AccessExclusiveLock

content/runbooks/rds/RDSDiskSpaceLimit.md
Add command to increase storage
Reduce lead time to increase storage
- Add command to increase storage
- Use `danger` style for disk storage increase hint
=> Add command to increase storage

charts/_source/templates/_helpers.tpl, charts/_source/templates/prometheusConfiguration.yaml, charts/_source/templates/prometheusRules.yaml, charts/_source/tests/prometheusRules_test.yaml, charts/_source/tests/values/with_keepFiringFor.yaml, charts/_source/values.yaml, charts/prometheus-postgresql-alerts/values.yaml, charts/prometheus-rds-alerts/values.yaml
Add `defaultKeepFiringFor` and `keepFiringFor` parameters to Helm chart and configure `keep_firing_for` attribute.
Users may need to customize the `keep_firing_for` Prometheus rule parameter for some alerts.
At Qonto, we need this parameter to keep alerts open during Pod rescheduling.
- Add `defaultKeepFiringFor` and `keepFiringFor` Helm parameters
=> Add parameters to customize keep_firing_for Prometheus rule

charts/prometheus-postgresql-alerts/prometheus_tests/SQLExporterDown.yml, charts/prometheus-postgresql-alerts/values.yaml
**Why:** only relying on Absent will miss the other case where exporter is down (no targets)
**How:** added alternative check
**Tests:** Ok
=> fix(alert): fix sql-exporter is Down alert

charts/prometheus-postgresql-alerts/prometheus_tests/PostgreSQLMaxConnections.yml, charts/prometheus-postgresql-alerts/values.yaml
The MR propose a fix to avoid printing actual values to prevent spamming alerting systems with new alerts. Instead, we simplify the description for easy recognition by the alerting system.
=> fix(PostgreSQLMaxConnections): remove value from alert description

charts/prometheus-rds-alerts/prometheus_tests/RDSLowDiskSpaceCount.yml, charts/prometheus-rds-alerts/values.yaml, content/runbooks/rds/RDSLowDiskSpaceCount.md
* **Goal:** add RDSLowDiskSpaceCount
* **Why:** we sometimes need alerting before we reach RDSDiskSpaceLimit alert
* **How:** added RDSLowDiskSpaceCount alert by account/region which shows up when there is at least 1 RDS instance under 20% free disk space. This alert doesn't appear under 10% to avoid duplicated alerts.
=> feat(RDS): create RDSLowDiskSpaceCount to display instances with less than 80% disk space

content/runbooks/rds/RDSLowDiskSpaceCount.md
In [`RDSLowDiskSpaceCount`][1], we have a link to `RDSDiskSpaceLimit`, but it is broken. This is due how [hugo][2] (which we use to render the documentation) deals with links.
To fix this, we need to use [`ref`][3].
[1]: https://qonto.github.io/database-monitoring-framework/0.2.2/runbooks/rds/RDSLowDiskSpaceCount/
[2]: https://gohugo.io/
[3]: https://gohugo.io/content-management/cross-references/
=> Fix RDSDiskSpaceLimit link
